CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS sensor_readings (
  reading_id bigint GENERATED BY DEFAULT AS IDENTITY,
  greenhouse_id text NOT NULL,
  sensor_id text NOT NULL,
  metric text NOT NULL,
  value double precision NOT NULL,
  unit text NOT NULL,
  measured_at timestamptz NOT NULL,
  PRIMARY KEY (reading_id, measured_at)
);

CREATE TABLE IF NOT EXISTS robot_state_history (
  history_id bigint GENERATED BY DEFAULT AS IDENTITY,
  robot_id text NOT NULL,
  status text NOT NULL,
  bed_id integer,
  battery_percent integer NOT NULL CHECK (battery_percent BETWEEN 0 AND 100),
  recorded_at timestamptz NOT NULL,
  PRIMARY KEY (history_id, recorded_at)
);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_metric_time
  ON sensor_readings(metric, measured_at DESC);

CREATE INDEX IF NOT EXISTS idx_robot_state_history_robot_time
  ON robot_state_history(robot_id, recorded_at DESC);

SELECT create_hypertable('sensor_readings', 'measured_at', if_not_exists => TRUE);
SELECT create_hypertable('robot_state_history', 'recorded_at', if_not_exists => TRUE);

INSERT INTO schema_migrations(version)
VALUES ('001_timeseries_schema')
ON CONFLICT (version) DO NOTHING;
